package extensions

func init() {
	RegisterTemplate(wailsReactTSTemplate{})
}

type wailsReactTSTemplate struct{}

func (wailsReactTSTemplate) Name() string        { return "wails-react-ts" }
func (wailsReactTSTemplate) Description() string { return "Wails + React + TypeScript desktop app" }
func (wailsReactTSTemplate) RootDir() string     { return "" }

// InitCommand returns the wails init command. The placeholder {{name}} will
// be replaced with the actual project name at runtime.
func (wailsReactTSTemplate) InitCommand() string { return "wails init -n {{name}} -t react-ts" }

// PreCreateDir returns false because wails init creates its own project directory
func (wailsReactTSTemplate) PreCreateDir() bool { return false }

func (wailsReactTSTemplate) Dependencies() []string {
	// Wails manages its own dependencies via the init command
	return nil
}

func (wailsReactTSTemplate) Files(projectName string) map[string]string {
	// Files are generated by the wails init command, no additional files needed
	return nil
}
